### ISSUE TITLE
Change dependencies

### ISSUE THREAD

**Issue by texastoland** [texastoland/nabs#1]
Old | New | Why
-|-|-
`jsonfile` | `read-pkg-up`/`write-pkg` | conventional, more npm-like
`winston` | ~~`loglevel`~~ `logging` | lightweight, fewer transitive dependencies

**Comment by artlogic** [comment]
I looked over `read-pkg-up` and `write-pkg` - this makes a lot of sense and gives nabs a nice new feature to boot. I'm all for this change.

I'm not as sure about moving away from `winston`. The thing I like about `winston` is the `cli` formatter it gives us access to. It looks like we might be able to use `logform` and integrate that directly with `loglevel` but that seems like a bit of work for essentially the same functionality. Is there another way to get nice looking cli output from `loglevel`?

**Comment by texastoland** [comment]
My use case is to export nabs with a configurable build "preset" (not boilerplate). It preconfigures sensible defaults and scripts for build, type, lint, format, etc. like I will PR for nabs. But nabs includes its transitive runtime dependencies (like logging).

loglevel can be formatted with a `factory` but I see your point. What do you think about [logging](https://yarnpkg.com/en/package/logging)? It uses Ava's formatter which I could reuse it for `--dry-run` and `--print-config`! I'll track features after the refactor.

<table>
<tr>
<th>Winston</th>
<th>logging</th>
<th>loglevel</th>
</tr>
<tr>
<td>
<pre>
info All dependencies
├─ async@2.6.1
├─ color-convert@1.9.2
├─ color-name@1.1.1
├─ color-string@1.5.3
├─ color@3.0.0
├─ colornames@1.1.1
├─ colors@1.3.1
├─ colorspace@1.1.1
├─ core-util-is@1.0.2
├─ diagnostics@1.1.1
├─ enabled@1.0.2
├─ env-variable@0.0.4
├─ fast-safe-stringify@2.0.5
├─ fecha@2.3.3
├─ inherits@2.0.3
├─ is-arrayish@0.3.2
├─ is-stream@1.1.0
├─ isarray@1.0.0
├─ kuler@1.0.0
├─ lodash@4.17.10
├─ logform@1.9.1
├─ ms@2.1.1
├─ one-time@0.0.4
├─ process-nextick-args@2.0.0
├─ safe-buffer@5.1.2
├─ simple-swizzle@0.2.2
├─ stack-trace@0.0.10
├─ string_decoder@1.1.1
├─ text-hex@1.0.0
├─ util-deprecate@1.0.2
├─ winston-transport@4.2.0
└─ winston@3.0.0
</pre>
</td>
<td>
<pre>
info All dependencies
├─ chalk@1.1.3
├─ debug@2.6.9
├─ escape-string-regexp@1.0.5
├─ esutils@2.0.2
├─ has-ansi@2.0.0
├─ logging@3.2.0
├─ ms@2.0.0
├─ nicely-format@1.1.0
├─ strip-ansi@3.0.1
└─ supports-color@2.0.0
</pre>
</td>
<td>
<pre>
info All dependencies
└─ loglevel@1.6.1
</pre>
</td>
</tr>
</table>

**Comment by artlogic** [comment]
> My use case is to export nabs with a configurable build "preset" (not boilerplate). It preconfigures sensible defaults and scripts for build, type, lint, format, etc. like I will PR for nabs. But nabs would necessarily export its transitive runtime dependencies (like logging).

I'd appreciate it if you would explain this a bit further. I like the idea of nabs.yaml presets, but I'm not exactly sure how this ties into transitive dependencies.

> loglevel can be formatted with a factory but I see your point. What do you think about logging? It uses Ava's formatter which I could reuse it for --dry-run and --print-config! I'll track features after the refactor.

I really like the idea of `logging` - but I don't see a way to set the log level. Am I missing that?

**Comment by texastoland** [comment]
> I like the idea of nabs.yaml presets

I've already got it spec'ed out!

> I'm not exactly sure how this ties into transitive dependencies.

Consider Babel or ESLint plugins. When you import one you import all its transitive dependencies too. That saves you from having to install a bunch of boilerplate yourself. Same idea with nabs. My personal project installs it as a runtime dependency so anyone (even if it's just me) who installs it gets nabs included. That means all its transitive dependencies too.

I think Winston is bloated. I see it for serious monitoring or linter-like tooling. nabs is so streamlined I searched for something lighter weight.

> I don't see a way to set the log level. Am I missing that?

Oh right I'll add it dylang/logging#10.

**Comment by artlogic** [comment]
> I think Winston is bloated. I see it for serious monitoring or linter-like tooling. nabs is so streamlined I searched for something lighter weight.

Winston is very big and nabs uses very little of it. Basically I reached for the first tool I had some familiarity with and didn't look back. I think it's a great idea to use something smaller.

I'm not really too concerned about transitive dependencies given the general state of most NPM packages, but I'm certainly not opposed to trying to control the bloat!

**Comment by texastoland** [comment]
I gave it more thought. I can write a short (< 20 lines) loglevel `factory` to do everything we both want. I'll circle back after the TypeScript port.
