### ISSUE TITLE
Check build

### ISSUE THREAD

**Issue by texastoland** [texastoland/nabs#4]
Dependency | Why
-|-
`eslint-plugin-shopify` | comprehensive rules and standard transitive dependencies
~~`flow-copy-source`~~ | copy source as with `.js.flow` extension for typings
`microbundle` | easy builds with types and standard transitive dependencies
`nabs` | stable version for own config
`prettier` | standard for formatting

**Comment by artlogic** [comment]
This all looks very reasonable, but why the change from `airbnb` to `shopify`?

**Comment by texastoland** [comment]
1. Transitive dependencies: Shopify includes everything you need making both `package.json` and `.eslintrc` much more readable.
2. TypeScript and Flow support: Airbnb has neither.
3. Strictness: Shopify is constantly (I know from contributing) adding rules to try to make the linter as helpful as possible.

**Comment by texastoland** [comment]
Here's my `.prettierrc`.

```
bracketSpacing: false
semi: false
trailingComma: all
```

I find semicolons noisy but I don't mind deleting the config if you prefer defaults.

**Comment by artlogic** [comment]
> Transitive dependencies: Shopify includes everything you need making both package.json and .eslintrc (even .babelrc) more "grokable".

I know a lot more people using airbnb than shopify and so my instinct is to stick with airbnb until the tide shifts. I can't seem to find a comparison of the two, so it's hard to know what advantages you're seeing. Do you have a sample project?

> TypeScript and Flow support: Airbnb has neither.

It seems that this is relatively easy to integrate, using `eslint-plugin-typescript`. 

> Strictness: Shopify is constantly (I've contributed) adding rules making the linter as helpful as possible.

I appreciate this - but I also can't find much that compares the rulesets. I'm inclined to stick with the more popular option unless shopify is significantly stricter.

***

I don't personally use prettier, as I prefer to just let the linter take care of it. I don't have a problem with it being included as a devDependency - as long as the linter would catch anything that prettier is fixing.

**Comment by texastoland** [comment]
> It seems that this is relatively easy to integrate, using `eslint-plugin-typescript`.

That's not all though. There's also the parser, custom rule sets, configuration, disabled rules either irrelevant or buggy in TypeScript, and overriding others so linting doesn't conflict with formatting. Speaking of transitive dependencies look [what it installs](https://github.com/Shopify/eslint-plugin-shopify/blob/33927aff81c34b472d793a179bd9b7cce9bba17f/package.json#L81-L98) (and configures) on your behalf.

> I'm inclined to stick with the more popular option unless shopify is significantly stricter.

I'm the opposite. Group think tends to not choose rationally or principally. Ignore stars a moment, click on <kbd>Contributors</kbd>, then <kbd>Pulse</kbd> in each repo. Don't you find it odd the difference in activity compared to number of users? Shopify is super invested in TS and the only company I'm aware of building anything comparable. I was also theirs was the only extended config for Flow.

> as long as the linter would catch anything that prettier is fixing

It's included in my scripts and also gets caught by the Prettier editor plugin. Do you have any opinions about the style rules I commented?

**Comment by artlogic** [comment]
I simply don't have time to exhaustively compare all the various options out there. I have to crowd source some decisions, and I decided awhile ago that linting was one of those decisions.

What I trying to avoid is a drastic change in code style. I mostly agree with the airbnb style guide and most of my projects adhere to that. If you can configure shopify so that it uses the same (or very similar) rules, then I'm willing to count this as an experiment to see if it would help my larger projects.

> Do you have any opinions about the style rules I commented?

My preference is to stick with defaults, except in the case of trailing commas (which is the default under airbnb).

**Comment by texastoland** [comment]
> I mostly agree with the airbnb style guide and most of my projects adhere to that

Whether it's Airbnb or Google (also popular) or Shopify they all basically agree. Formatting is the domain of Prettier.

**Comment by artlogic** [comment]
So you don't believe the linter should be enforcing formatting rules?

**Comment by texastoland** [comment]
Of course not? Linting enforces semantic correctness. Type checking enforces statically analyzable correctness. Formatting enforces layout and without altering semantics. There are more tools down the pipeline. ESLint filled the role of a formatter for lack of alternatives but Prettier is already standard. Prettier works the same in regards to flagging errors in the editor, before a build, and offering to fix them. Prettier works fundamentally different from ESLint. ESLint checks patterns. Prettier just overwrites everything. It's the strictest form of consistency. No room for bikeshedding about code style at all.

**Comment by texastoland** [comment]
PS we can PR here first or in a `develop` branch if you feel unsure.

**Comment by artlogic** [comment]
In the JS community we've been oscillating between "linter does everything" to "linter checks semantics and we want separate tools for other things" for years.  JSCS was a thing before ESLint and the community decided that they wanted one tool instead of two. As recently as last Fall there's still a fair amount of contention over which is the "right way" as evidenced by this thread: https://github.com/airbnb/javascript/issues/1548

I respect your opinion and even find myself moving towards it - but I'm also not entirely ready to change all my tooling just yet.

Please shoot me an email - let's talk a bit more about how we're going to move forward here: james@kruth.org

**Comment by texastoland** [comment]
> contention over which is the "right way" as evidenced by this thread: airbnb/javascript#1548

I disagree. The nicest thing I can say is the poster is informed and the contributor is uninformed. I actually believe the contributor was defensive and ignorant about the difference between how formatters are implemented from linters. That's why the conversation was locked.

Shopify deals with it the way the poster proposed. There's an extra preset to disable style rules for use with Prettier. Shopify uses `eslint-plugin-prettier` to apply lint style _after_ formatting. My perspective is that kind of customization is silly. Conventions exist for consistency (`bracketSpacing: false`), readability (`semi: false), and ease of editing (`trailingComma: all). Any other opinion is unproductive.

No matter how you format your code Prettier will output it the same. It does so because its parse tree doesn't preserve original formatting. ESLint must preserve formatting. It only checks or fixes matching nodes in its parse tree. It's simply not feasible nor recommendable to use ESLint with the expectation it works like Prettier. Prettier also formats [a bunch of other files](https://prettier.io/docs/en/index.html).
